#! /usr/bin/env python3

from robot_controller.robot_controller_node import RobotControllerNode
import rospy

def main():
    node = RobotControllerNode()

    rospy.logerr(rospy.get_param_names())

    goal_x = rospy.get_param("/goal_x")
    goal_y = rospy.get_param("/goal_y")
    goal_yaw = rospy.get_param("/goal_yaw")

    answer = node.set_goal(goal_x, goal_y, goal_yaw)
    rospy.logerr(answer)

if __name__ == '__main__':
    main()
